all:
  hosts:
    node1:
      ansible_host: 158.160.16.34
      ansible_user: phenom
    node2:
      ansible_host: 84.252.139.128
      ansible_user: phenom
    node3:
      ansible_host: 130.193.43.183
      ansible_user: phenom
    node4:
      ansible_host: 84.252.143.162
      ansible_user: phenom
    node5:
      ansible_host: 62.84.122.145
      ansible_user: phenom
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
